config/routes.rb
Blog::Application.routes.draw do
  get "static_pages/about"
  get "static_pages/resources"
  get "static_pages/admin"
  
  resources :items

  root  :to => "items#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :title, :body, :image

  	has_attached_file :image, :styles => { :medium => "500x500>", :thumb => "100x100>" }

end

app/models/static_pages.rb
class StaticPages < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def index
		@all_posts = Item.find(:all, :order => "created_at desc")
	end

	def show
		@all_posts = Item.find(:all, :order => "created_at desc")
		@item = Item.find(params[:id])
	end

	def new
		@item = Item.new
	end
	
	def create
  		@item = Item.new(params[:item])
  		@item.save
  		flash.notice = "Article '#{@item.title}' Created!"
  		redirect_to item_path(@item)
	end

	def destroy
		@item = Item.find(params[:id])
		@item.destroy
		flash.notice = "Article '#{@item.title}' Deleted!"
		redirect_to items_path
	end

	def edit
		@item = Item.find(params[:id])
	end

	def update 
		@item = Item.find(params[:id])
		@item.update_attributes(params[:item])

		flash.notice = "Article '#{@item.title}' Updated!"

		redirect_to item_path(@item)
	end
	


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def admin
  	@item = Item.new
  	@items = Item.all
  end

  def about
  end

  def resources
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/items/_disqus.html.erb
  <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'becomingaunicorn'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
    

app/views/items/_form.html.erb
<%= form_for(@item, html: {multipart: true}) do |f| %>
  <ul>
  <% @item.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>

  <p>
    <% if @item.image.exists? %>
        <%= image_tag @item.image.url %><br/>
    <% end %>
    <%= f.label :image, "Attach a New Image" %><br />
    <%= f.file_field :image %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/items/edit.html.erb
<h1>Edit an Article</h1>
<%= render partial: 'form' %>

app/views/items/index.html.erb
<div id="container" class="container">	

	<%= render 'layouts/menu_panel' %>

	<div class="side-panel">
		<ul id="side-toc" class="side-toc">
			<li><a href="static_pages/about">About</a></li>
			<li><a href="static_pages/resources">Resources</a></li>
		</ul>
	</div>


	<div class="bb-custom-wrapper">
		<div id="bb-bookblock" class="bb-bookblock">
			<% @all_posts.each do |post| %>
				<div class="bb-item" id="item1">
					<div class="content">
						<div class="scroller">
							<h2><%= post.title %></h2>
							<p><%= post.body %></p>
							<%= render 'items/disqus' %>
						</div>
					</div>
				</div>
			<% end %>
			
		</div>

		<nav>
		<ul>
		<li><span id="bb-nav-prev">
			<%= image_tag('prev.png', :size=>'40x40') %>
		</span></li>
		<li><span id="bb-nav-next">
			<%= image_tag('next.png', :size=>'40x40') %>
		</span></li>
		</li>
		</nav>

		
		<span id="tblcontents" class="menu-button">
			<%= image_tag('menu.png', :size=>'40x40') %>
		</span>
		<span id="sidecontents" class="side-button">
			<%= image_tag('more.png', :size=>'40x40') %>
		</span>
		

	</div>
	</div><!-- /container -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<%= javascript_include_tag('jquery.mousewheel') %>
<%= javascript_include_tag('jquery.jscrollpane.min') %>
<%= javascript_include_tag('jquerypp.custom') %>
<%= javascript_include_tag('jquery.bookblock') %>
<%= javascript_include_tag('page') %>
<script>
	$(function() {

		Page.init();

	});
</script>

app/views/items/new.html.erb
<h1>Create a New Article</h1>
<%= render partial: 'form' %>

app/views/items/show.html.erb
<div id="container" class="container">	

	<%= render 'layouts/menu_panel' %>

	<div class="side-panel">
		<ul id="side-toc" class="side-toc">
			<li><a href="static_pages/about">About</a></li>
			<li><a href="static_pages/resources">Resources</a></li>
		</ul>
	</div>

	<div class="bb-custom-wrapper">
		<div id="bb-bookblock" class="bb-bookblock">
			<div class="bb-item" id="item1">
				<div class="content">
					<div class="scroller">
						<h2><%= @item.title %></h2>
						<p><%= @item.body %></p>
						<% if @item.image.exists? %>
      						<%= image_tag @item.image.url (:medium) %><br/>
 						<% end %>
						<%= button_to "delete", item_path(@item), :method => :delete, confirm: "Really delete the article?" %>
						<%= link_to "edit", edit_item_path(@item) %>
						<%= render 'items/disqus' %>

					</div>
				</div>
			</div>
			
		</div>

		<nav>
		<ul>
		<li><span id="bb-nav-prev">
			<%= image_tag('prev.png', :size=>'40x40') %>
		</span></li>
		<li><span id="bb-nav-next">
			<%= image_tag('next.png', :size=>'40x40') %>
		</span></li>
		</li>
		</nav>

		
		<span id="tblcontents" class="menu-button">
			<%= image_tag('menu.png', :size=>'40x40') %>
		</span>
		<span id="sidecontents" class="side-button">
			<%= image_tag('more.png', :size=>'40x40') %>
		</span>
		

	</div>
	</div><!-- /container -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<%= javascript_include_tag('jquery.mousewheel') %>
<%= javascript_include_tag('jquery.jscrollpane.min') %>
<%= javascript_include_tag('jquerypp.custom') %>
<%= javascript_include_tag('jquery.bookblock') %>
<%= javascript_include_tag('page') %>
<script>
	$(function() {

		Page.init();

	});
</script>

app/views/layouts/_menu_panel.html.erb
<div class="menu-panel">
	<h3>Becoming a Unicorn</h3>
	<ul id="menu-toc" class="menu-toc">
		<% @all_posts.each do |item| %>
			<li>
				<%= link_to item.title, item_path(item) %>
			</li>
		<% end %>				
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
	<meta charset="UTF-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
	<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
	<title>Becoming a Unicorn</title>
	<%= stylesheet_link_tag('jquery.jscrollpane.custom') %>
	<%= stylesheet_link_tag('bookblock') %>
	<%= stylesheet_link_tag('custom') %>
	<%= javascript_include_tag('modernizr.custom.79639') %>
</head>
<body>
	<p class="flash"><%= flash.notice %></p>

	<%= yield %>

</body>
</html>

app/views/static_pages/about.html.erb
<!doctype html>
<head>
	<meta charset="utf-8">
	<title>About</title>
	
	<script src="js/about.js"></script>
	<%= stylesheet_link_tag('about') %>
</head>

<body>


<div id="unicorn">
	<%= image_tag('me_2.png', :size=>'180x180') %>
</div>

<h1>Hello
<br>
I'm Gulnara
</h1>

<p>This is my first Rails App.</p>
<p>This project will be my sand box, where I test things I learn about Ruby on Rails.</p>
<p>I will be covering all aspects of this and other projects on my blog <a href="http://gulnara.me">Becoming a Unicorn</a>.
 <br> 
If you want to know more about how it all started, read my
<br>
<a href="http://gulnara.me/post/42818343585/how-it-all-began-or-why-a-banker-decides-to-become-a">1st post</a>.
<br> 
If you have something to share, email me at
<br>
gulnara@gulnara.me
<br>
<br>
connect with me</p>

<div id="social-media-icons">
	<ul>
		<li class="twitter">
			<a href="https://twitter.com/Gulnara" target="_blank">
				<%= image_tag('twitter.png', :size=>'50x50') %>
			</a>
		</li>
		<li class="dribble">
			<a href="http://dribbble.com/Gulnara" target="_blank">
				<%= image_tag('dribble.png', :size=>'50x50') %>
			</a>
		</li>
		<li class="behance">
			<a href="http://www.behance.net/lyulyoka" target="_blank">
				<%= image_tag('behance.png', :size=>'50x50') %>
			</a>
		</li>
		<li class="linkedin">
			<a href="http://www.linkedin.com/in/gulnaram/" target="_blank">
				<%= image_tag('linkedin.png', :size=>'50x50') %>
			</a>
		</li>
		<li class="rss">
			<a href="#" target="_blank">
				<%= image_tag('rss.png', :size=>'50x50') %>
			</a>
		</li>
	</ul>
</div>

<div class="test">
</div>


</body>

app/views/static_pages/admin.html.erb
<h1>Admin Control</h1>
<h2>Create a New Article</h2>
<%= render partial: 'items/form' %>
<h2>List of Posts</h2>
<ul>
	<% @items.each do |item| %>
		<li>
			<%= link_to item.title, item_path(item), class: 'item_title' %>
		</li>
	<% end %>
</ul>

app/views/static_pages/resources.html.erb
<!doctype html>
<head>
	<meta charset="utf-8">
	<title>Resources</title>

	<script src="js/about.js"></script>
	<%= stylesheet_link_tag('resources') %>
</head>

<body>


<h1>Coming Soon!
</h1>

<p>In the meantime check-out my blog <a href="http://gulnara.me/"> "Becoming a Unicorn"</a>!</p>

<div id="blog">
				<a href="http://gulnara.me/"><%= image_tag('blog.png', :size=>'50x50') %></a>
</div>


</body>